server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false