version: '3.8'

services:
  postgres-user:
    image: postgres:15-alpine
    container_name: shopsphere-postgres-user
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh@postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-product:
    image: postgres:15-alpine
    container_name: shopsphere-postgres-product
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh@postgres
      POSTGRES_DB: product_service_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-inventory:
    image: postgres:15-alpine
    container_name: shopsphere-postgres-inventory
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh@postgres
      POSTGRES_DB: inventory_service_db
    ports:
      - "5434:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-user-data:
  postgres-product-data:
  postgres-inventory-data: