version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - CLUSTER_ID=ciWW7b2-Q2e7a3V3LhVb6w

  postgres-user:
    image: postgres:15-alpine
    container_name: shopsphere-postgres-user
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh@postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-product:
    image: postgres:15-alpine
    container_name: shopsphere-postgres-product
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh@postgres
      POSTGRES_DB: product_service_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-inventory:
    image: postgres:15-alpine
    container_name: shopsphere-postgres-inventory
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh@postgres
      POSTGRES_DB: inventory_service_db
    ports:
      - "5434:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-order:
    image: postgres:15-alpine
    container_name: shopsphere-postgres-order
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh@postgres
      POSTGRES_DB: order_service_db
    ports:
      - "5435:5432" # Host port 5435
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    restart: unless-stopped



volumes:
  postgres-user-data:
  postgres-product-data:
  postgres-inventory-data:
  postgres-order-data: