server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888/"

  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/register, /api/v1/users/login

        # Secured User Routes (Requires Filter)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        
        # Public Product Routes (No Auth Required)
        - id: product-service-public
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
            - Method=GET

        # Secured Product Routes (Auth Required)
        - id: product-service-secured
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
            - Method=POST, PUT, DELETE
          filters:
            - AuthenticationFilter

        # Public Inventory Route (Checking Stock)
        - id: inventory-service-public
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
            - Method=GET

        # Secured Inventory Routes (Adding/Modifying Stock)
        - id: inventory-service-secured
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
            - Method=POST
          filters:
            - AuthenticationFilter

        # Secured Order Route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter

        # Secured Cart Route
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - AuthenticationFilter

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}