server:
  port: 8082

spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8888/"

  datasource:
    url: jdbc:postgresql://localhost:5433/product_service_db
    username: vansh
    password: vansh@postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/